import { Outfit } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Auth Credentials Provider",
  description: "Generated by create next app",
  icons: {
    icon: ["/logo.svg"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <main className="max-w-[1440px] m-auto">
          {children}
          <Toaster />
        </main>
      </body>
    </html>
  );
}
